# GENERAL
MODEL_DIR  : '../model'
RESULT_DIR : '../result'
DATASET_DIR: '../dataset'

# FEATURE EXTRACTION
EXTRACTION_METHOD: 'mel'
N_FFT            : 8192
HOP_LENGTH       : 4096
N_MELS           : 80

# MODEL PARAMS
KERNEL: 'rbf'
GAMMA : 'scale'
NU    : 0.002

# TESTING
TESTING_TYPE       : 'dev' # NOTE: 'dev' for development testing, 'final' for the final testing for scoring.
DEV_NORMAL_SAMPLES : 120
DEV_ANOMALY_SAMPLES: 30
